version: "3.9"
   
services:
  postgres:
    image: postgres:14.0-alpine
    deploy:
      resources:
          limits:
            memory: 500M
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=Gaman
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: always

  django:
    build: .
    volumes:
      - .:/code
    deploy:
      resources:
          limits:
            memory: 500M
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    command: /code/compose/django/start.sh
    restart: always

volumes:
  postgres: