version: "3"

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: gaman_production_postgres
    deploy:
      resources:
        limits:
          memory: 350M
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file: ./.env
    ports:
      - "5432:5432"
    restart: always
    container_name: postgres

  redis:
    image: redis:6.2.6-alpine
    deploy:
      resources:
        limits:
          memory: 350M
    container_name: redis

  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: gaman_local_django
    volumes:
      - .:/app
    env_file:
      - ./.env
    deploy:
      resources:
        limits:
          memory: 350M
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    command: /start
    restart: always
    container_name: django

  celeryworker:
    <<: *django
    image: gaman_local_celeryworker
    volumes:
      - .:/app
    deploy:
      resources:
        limits:
          memory: 350M
    ports: []
    depends_on:
      - redis
      - django
    command: /start-celeryworker
    restart: always
    container_name: celery-worker
