version: "3"

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: gaman_production_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file: ./.env
    ports:
      - "5432:5432"
    restart: always
    container_name: postgres

  redis:
    image: redis:6.2.6-alpine
    container_name: redis

  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: gaman_production_django
    volumes:
      - .:/app
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    command: /start
    restart: always
    container_name: django

  celeryworker:
    <<: *django
    image: gaman_production_celeryworker
    volumes:
        - .:/app
    ports: []
    depends_on:
      - redis
      - django
    command: /start-celeryworker
    restart: always
    container_name: celery-worker
  
  flower:
    <<: *django
    image: gaman_production_flower
    ports:
      - "5555:5555"
    command: /start-flower
    container_name: flower
