# Generated by Django 3.2.8 on 2021-10-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='public',
            field=models.BooleanField(default=True, help_text='Profile privacy'),
        ),
    ]
