# Generated by Django 3.2.8 on 2021-10-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Athlete', 'Athlete'), ('Sponsor', 'Sponsor'), ('Coach', 'Coach'), ('League president', 'League president')], help_text='role of user.', max_length=16),
        ),
    ]
