# Generated by Django 3.2.8 on 2021-10-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_followrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Date time on which the was updated.', verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Date time on which the was updated.', verbose_name='updated at'),
        ),
    ]
