# Generated by Django 4.0.1 on 2022-01-29 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the was created.', verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Date time on which the was updated.', verbose_name='updated at')),
                ('text', models.TextField(help_text='write a comment', max_length=250)),
                ('reactions', models.PositiveBigIntegerField(default=0)),
                ('type', models.CharField(choices=[('Principal-Comment', 'Principal-Comment'), ('Reply', 'Reply')], max_length=17)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='CommentReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the was created.', verbose_name='created at')),
                ('reaction', models.CharField(choices=[('Like', 'Like'), ('Love', 'Love'), ('Curious', 'Curious'), ('Haha', 'Haha'), ('Sad', 'Sad'), ('Angry', 'Angry')], help_text='react to a object', max_length=7)),
            ],
            options={
                'ordering': ['-created'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the was created.', verbose_name='created at')),
                ('content', models.ImageField(blank=True, help_text='Post picture', null=True, upload_to='posts/pictures/%Y/%m/%d/')),
            ],
            options={
                'ordering': ['-created'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the was created.', verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Date time on which the was updated.', verbose_name='updated at')),
                ('about', models.TextField(blank=True, help_text='Write something')),
                ('privacy', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', help_text="Post's Privacy", max_length=7)),
                ('location', models.CharField(blank=True, help_text='Where are you?', max_length=60)),
                ('feeling', models.CharField(blank=True, choices=[('Happy', 'Happy'), ('Loved', 'Loved'), ('Excited', 'Excited'), ('Crazy', 'Crazy'), ('Thankful', 'Thankful'), ('Fantastic', 'Fantastic'), ('Motived', 'Motived'), ('Tired', 'Tired'), ('Alone', 'Alone'), ('Angry', 'Angry'), ('Sorry', 'Sorry'), ('Confused', 'Confused'), ('Strong', 'Strong'), ('Stressed', 'Stressed'), ('Scared', 'Scared'), ('Sick', 'Sick'), ('Sarcastic', 'Sarcastic'), ('Anxious', 'Anxious'), ('Nostalgic', 'Nostalgic'), ('Proud', 'Proud'), ('Curious', 'Curious'), ('Surprised', 'Surprised')], help_text='How you feel?', max_length=9)),
                ('reactions', models.PositiveBigIntegerField(default=0)),
                ('comments', models.PositiveBigIntegerField(default=0)),
                ('shares', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created', '-updated'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the was created.', verbose_name='created at')),
                ('content', models.FileField(blank=True, help_text='Post video', null=True, upload_to='posts/videos/%Y/%m/%d/')),
            ],
            options={
                'ordering': ['-created'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the was created.', verbose_name='created at')),
                ('reaction', models.CharField(choices=[('Like', 'Like'), ('Love', 'Love'), ('Curious', 'Curious'), ('Haha', 'Haha'), ('Sad', 'Sad'), ('Angry', 'Angry')], help_text='react to a object', max_length=7)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
            options={
                'ordering': ['-created'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
