# Generated by Django 3.2.9 on 2021-11-19 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sponsorships', '0001_initial'),
        ('sports', '0001_initial'),
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postreaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sponsorships.brand'),
        ),
        migrations.AddField(
            model_name='post',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sports.club'),
        ),
        migrations.AddField(
            model_name='post',
            name='pictures',
            field=models.ManyToManyField(blank=True, to='posts.Picture'),
        ),
        migrations.AddField(
            model_name='post',
            name='post',
            field=models.ForeignKey(help_text='Post to be republished.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='re_post', to='posts.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='tag_users',
            field=models.ManyToManyField(blank=True, related_name='tag_friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='videos',
            field=models.ManyToManyField(blank=True, to='posts.Video'),
        ),
        migrations.AddField(
            model_name='commentreaction',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.comment'),
        ),
        migrations.AddField(
            model_name='commentreaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='replies',
            field=models.ManyToManyField(blank=True, help_text='Replies of the comment.', related_name='responses', to='posts.Comment'),
        ),
        migrations.CreateModel(
            name='PrincipalComment',
            fields=[
            ],
            options={
                'ordering': ['-reactions', 'created'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('posts.comment',),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
            ],
            options={
                'ordering': ['created'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('posts.comment',),
        ),
    ]
