# Generated by Django 3.2.8 on 2021-10-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment_commentreaction_postreaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Date time on which the was updated.', verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Date time on which the was updated.', verbose_name='updated at'),
        ),
    ]
