# Generated by Django 3.2.8 on 2021-10-17 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20211016_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag_friends',
            new_name='tag_users',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.ForeignKey(help_text='Comment that is being replied.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='principal_comment', to='posts.comment'),
        ),
    ]
