# Generated by Django 3.2.8 on 2021-10-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20211016_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='replies',
            field=models.ManyToManyField(blank=True, help_text='Replies of the comment.', related_name='_posts_comment_replies_+', to='posts.Comment'),
        ),
    ]
