# Generated by Django 3.2.8 on 2021-10-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the was created.', verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Date time on which the was updated.', verbose_name='updated at')),
                ('slugname', models.SlugField(unique=40)),
                ('about', models.TextField(blank=True, help_text='write about something')),
                ('official_web', models.URLField(blank=True, help_text='Web site')),
                ('photo', models.ImageField(blank=True, help_text='brand photo', null=True, upload_to='brands/photos/%Y/%m/%d/')),
                ('cover_photo', models.ImageField(blank=True, help_text='brand cover photo', null=True, upload_to='brands/cover_photos/%Y/%m/%d/')),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created', '-updated'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the was created.', verbose_name='created at')),
                ('comment', models.CharField(blank=True, max_length=250)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=1)),
            ],
            options={
                'ordering': ['-created'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the was created.', verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Date time on which the was updated.', verbose_name='updated at')),
                ('start', models.DateField(help_text='sponsorship start date')),
                ('finish', models.DateField(help_text='sponsorship finish date')),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created', '-updated'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
