# Generated by Django 4.0.1 on 2022-01-24 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorships', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sports', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the was created.', verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Date time on which the was updated.', verbose_name='updated at')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('photo', models.ImageField(blank=True, help_text='Event picture', null=True, upload_to='sports/events/pictures/%Y/%m/%d/')),
                ('start', models.DateField(help_text='sport event start date')),
                ('finish', models.DateField(help_text='sport event finish date')),
                ('geolocation', models.CharField(max_length=33)),
                ('assistants', models.ManyToManyField(blank=True, related_name='assistants', to=settings.AUTH_USER_MODEL)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sponsorships.brand')),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sports.club')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-updated'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
