# Generated by Django 4.0.1 on 2022-01-29 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sponsorships', '0002_initial'),
        ('sports', '0003_sportevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportevent',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sponsorships.brand'),
        ),
        migrations.AlterField(
            model_name='sportevent',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sports.club'),
        ),
        migrations.AlterField(
            model_name='sportevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
